Субмодули, исправления ошибок, доработка пунктов навигации
easterism/core2 pull request #130
Opened 2020-09-16 09:54 UTC by shabuninil

2020-09-28 21:57 UTC, easterism reviewed
Как сюда успела проникнуть регистрация??

2020-10-15 08:44 UTC, easterism commented on html/material/login/indexMobile.html
> +    <script src="core2/html/material/js/sweetalert2.min.js?_=2"></script>
не должно подключаться, если не задана возможность регистрации

2020-10-15 08:44 UTC, easterism commented on html/material/login/indexMobile.html
> +    <script src="core2/js/jquery.maskedinput.min.js"></script>
не должно подключаться, если не задана возможность регистрации

2020-10-15 09:36 UTC, shabuninil commented on html/material/login/indexMobile.html
> +    <script src="core2/js/jquery.maskedinput.min.js"></script>
уберем

2020-10-29 14:07 UTC, easterism commented on html/default/login/indexMobile.html
>  	<link rel="icon" type="image/png" href="[FAVICON_PNG]"/>
откуда опять [FAVICON_PNG]

2020-11-10 12:17 UTC, shabuninil commented on html/material/login/indexMobile.html
> +    <script src="core2/js/jquery.maskedinput.min.js"></script>
убрано

2020-11-10 12:17 UTC, shabuninil commented on html/default/login/indexMobile.html
>  	<link rel="icon" type="image/png" href="[FAVICON_PNG]"/>
убрано

2020-11-10 21:09 UTC, easterism requested changes

2020-11-10 21:09 UTC, easterism commented on html/default/login/indexMobile.html
>  	<link rel="icon" type="image/png" href="[FAVICON_PNG]"/>
а в indexMobile.html

2020-11-11 15:09 UTC, easterism approved these changes

2020-11-11 15:09 UTC, merged