123
easterism/core2 pull request #133
Opened 2020-11-30 15:12 UTC by shabuninil

2020-12-01 06:50 UTC, easterism requested changes
вайлы .mo не должны быть под версией

2020-12-23 09:09 UTC, easterism requested changes

2020-12-23 09:09 UTC, easterism commented on inc/classes/class.list.php
> +                                        $search .= " AND DATE_FORMAT({$next['field']}, '%Y-%m-%d') >= ? AND DATE_FORMAT({$next['field']}, '%Y-%m-%d') < ?";
Почему так?

2020-12-23 09:10 UTC, shabuninil commented on inc/classes/class.list.php
> +                                        $search .= " AND DATE_FORMAT({$next['field']}, '%Y-%m-%d') >= ? AND DATE_FORMAT({$next['field']}, '%Y-%m-%d') < ?";
А как?

2021-01-19 08:33 UTC, easterism approved these changes

2021-01-19 08:39 UTC, easterism requested changes

2021-01-19 08:39 UTC, easterism commented on inc/classes/class.list.php
> +                                        $search .= " AND DATE_FORMAT({$next['field']}, '%Y-%m-%d') >= ? AND DATE_FORMAT({$next['field']}, '%Y-%m-%d') < ?";
надо оставить BETWEEN

2021-01-19 08:42 UTC, shabuninil commented on inc/classes/class.list.php
> +                                        $search .= " AND DATE_FORMAT({$next['field']}, '%Y-%m-%d') >= ? AND DATE_FORMAT({$next['field']}, '%Y-%m-%d') < ?";
это старый комит. BETWEEN давно возвращен

2021-01-19 12:09 UTC, merged

2021-01-19 12:10 UTC, easterism approved these changes